import type { Metadata } from "next";
import { Amiri } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const amiri = Amiri({
  weight: ["400", "700"],
});
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  IconBrandTelegram,
  IconBrandInstagram,
  IconBrandFacebook,
  IconBrandYoutube,
  IconBrandX,
} from "@tabler/icons-react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function SocialMedia() {
  return (
    <div className="flex space-x-4 space-x-reverse">
      <Link
        href="#"
        className="text-cream hover:text-sage transition-colors duration-300"
      >
        <IconBrandFacebook size={24} />
      </Link>
      <Link
        href="#"
        className="text-cream hover:text-sage transition-colors duration-300"
      >
        <IconBrandInstagram size={24} />
      </Link>
      <Link
        href="#"
        className="text-cream hover:text-sage transition-colors duration-300"
      >
        <IconBrandYoutube size={24} />
      </Link>
      <Link
        href="#"
        className="text-cream hover:text-sage transition-colors duration-300"
      >
        <IconBrandX size={24} />
      </Link>
      <Link
        href="#"
        className="text-cream hover:text-sage transition-colors duration-300"
      >
        <IconBrandTelegram size={24} />
      </Link>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={amiri.className}>
        <div className="min-h-screen flex flex-col bg-cream text-forest font-arabic">
          <header className="bg-forest text-cream py-4 sticky top-0 z-50 shadow-md">
            <nav className="container mx-auto flex justify-between items-center px-4">
              <Link
                href="/"
                className="text-2xl font-bold hover:text-sage transition-colors duration-300"
              >
                مقرأة للإمام نافع
              </Link>
              <ul className="hidden md:flex space-x-6 space-x-reverse">
                <li>
                  <Link
                    href="/registration"
                    className="hover:text-sage transition-colors duration-300"
                  >
                    التسجيل
                  </Link>
                </li>
                <li>
                  <Link
                    href="/test-results"
                    className="hover:text-sage transition-colors duration-300"
                  >
                    نتائج الاختبار
                  </Link>
                </li>
                <li>
                  <Link
                    href="/subjects"
                    className="hover:text-sage transition-colors duration-300"
                  >
                    المواضيع
                  </Link>
                </li>
                <li>
                  <Link
                    href="/reading-progress"
                    className="hover:text-sage transition-colors duration-300"
                  >
                    نظام تقدم القراءة
                  </Link>
                </li>
                <li>
                  <Link
                    href="/publications"
                    className="hover:text-sage transition-colors duration-300"
                  >
                    المنشورات والمقالات
                  </Link>
                </li>
              </ul>
              <SocialMedia />
              {/* <Button className="bg-sage hover:bg-cream hover:text-forest transition-colors duration-300"> */}
              {/*   تسجيل الدخول */}
              {/* </Button> */}
            </nav>
          </header>
          <main className="flex-grow">{children}</main>
          <footer className="bg-forest text-cream py-12">
            <div className="container mx-auto px-4">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                <div>
                  <h3 className="text-xl font-bold mb-4">عن مقرأة</h3>
                  <p className="mb-4">
                    نحن نسعى لتوفير أفضل تجربة تعليمية في مجال القراءة والتجويد
                    للطلاب في جميع أنحاء العالم.
                  </p>
                  <SocialMedia />
                </div>
                <div>
                  <h3 className="text-xl font-bold mb-4">روابط سريعة</h3>
                  <ul className="space-y-2">
                    <li>
                      <Link
                        href="/about"
                        className="hover:text-sage transition-colors duration-300"
                      >
                        عن الغرفة
                      </Link>
                    </li>
                    <li>
                      <Link
                        href="/courses"
                        className="hover:text-sage transition-colors duration-300"
                      >
                        الدورات
                      </Link>
                    </li>
                    <li>
                      <Link
                        href="/teachers"
                        className="hover:text-sage transition-colors duration-300"
                      >
                        المعلمون
                      </Link>
                    </li>
                    <li>
                      <Link
                        href="/faq"
                        className="hover:text-sage transition-colors duration-300"
                      >
                        الأسئلة الشائعة
                      </Link>
                    </li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-xl font-bold mb-4">اتصل بنا</h3>
                  <p>البريد الإلكتروني: info@imamnafi.com</p>
                  <p>الهاتف: +123 456 7890</p>
                  <p>العنوان: شارع القراء، المدينة المنورة</p>
                </div>
                <div>
                  <h3 className="text-xl font-bold mb-4">النشرة الإخبارية</h3>
                  <p className="mb-4">
                    اشترك للحصول على آخر الأخبار والتحديثات
                  </p>
                  <form className="flex space-x-2 space-x-reverse">
                    <Input
                      type="email"
                      placeholder="بريدك الإلكتروني"
                      className="bg-cream text-forest"
                    />
                    <Button
                      type="submit"
                      className="bg-sage hover:bg-cream hover:text-forest"
                    >
                      اشتراك
                    </Button>
                  </form>
                </div>
              </div>
              <div className="mt-8 pt-8 border-t border-sage text-center">
                <p>
                  &copy; {new Date().getFullYear()} مقرأة للإمام نافع. جميع
                  الحقوق محفوظة.
                </p>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
